[workspace]
members = [
    "crates/tokenjar-core",
    "crates/tokenjar-cli",
]
resolver = "2"

[workspace.package]
version = "1.1.1"
edition = "2021"
authors = ["Ömer Faruk Eskitürk"]
license = "BUSL-1.1"
repository = "https://github.com/Farukes/TokenJar"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
